namespace View
{
    namespace MenuModule
    {
        partial class MainMenu
        {
            /// <summary>
            /// Required designer variable.
            /// </summary>
            private System.ComponentModel.IContainer components = null;

            /// <summary>
            /// Clean up any resources being used.
            /// </summary>
            /// <param name="disposing">true if managed resources should be disposed; otherwise, false.</param>
            protected override void Dispose(bool disposing)
            {
                if (disposing && (components != null))
                {
                    components.Dispose();
                }
                base.Dispose(disposing);
            }

            #region Windows Form Designer generated code

            /// <summary>
            /// AUTO GENERATED BY C# VISUAL STUDIO
            /// Required method for Designer support - do not modify
            /// the contents of this method with the code editor.
            /// </summary>
            private void InitializeComponent()
            {
                this.Start = new System.Windows.Forms.Button();
                this.Instructions = new System.Windows.Forms.Button();
                this.Exit = new System.Windows.Forms.Button();
                this.SuspendLayout();
                // 
                // Start
                // 
                this.Start.BackColor = System.Drawing.Color.Transparent;
                this.Start.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
                this.Start.FlatAppearance.BorderSize = 0;
                this.Start.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
                this.Start.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
                this.Start.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
                this.Start.Font = new System.Drawing.Font("Lucida Console", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
                this.Start.ForeColor = System.Drawing.Color.White;
                this.Start.Location = new System.Drawing.Point(264, 258);
                this.Start.Name = "Start";
                this.Start.Size = new System.Drawing.Size(168, 44);
                this.Start.TabIndex = 0;
                this.Start.UseVisualStyleBackColor = false;
                this.Start.Click += new System.EventHandler(this.Start_Click);
                // 
                // Instructions
                // 
                this.Instructions.BackColor = System.Drawing.Color.Transparent;
                this.Instructions.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
                this.Instructions.FlatAppearance.BorderSize = 0;
                this.Instructions.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
                this.Instructions.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
                this.Instructions.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
                this.Instructions.Font = new System.Drawing.Font("Lucida Console", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
                this.Instructions.ForeColor = System.Drawing.Color.White;
                this.Instructions.Location = new System.Drawing.Point(264, 304);
                this.Instructions.Name = "Instructions";
                this.Instructions.Size = new System.Drawing.Size(168, 44);
                this.Instructions.TabIndex = 1;
                this.Instructions.UseVisualStyleBackColor = false;
                this.Instructions.Click += new System.EventHandler(this.howToPlay_Click);
                // 
                // Exit
                // 
                this.Exit.BackColor = System.Drawing.Color.Transparent;
                this.Exit.FlatAppearance.BorderColor = System.Drawing.Color.FromArgb(((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
                this.Exit.FlatAppearance.BorderSize = 0;
                this.Exit.FlatAppearance.MouseDownBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
                this.Exit.FlatAppearance.MouseOverBackColor = System.Drawing.Color.FromArgb(((int)(((byte)(80)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))), ((int)(((byte)(0)))));
                this.Exit.FlatStyle = System.Windows.Forms.FlatStyle.Flat;
                this.Exit.Font = new System.Drawing.Font("Lucida Console", 15.75F, System.Drawing.FontStyle.Regular, System.Drawing.GraphicsUnit.Point, ((byte)(0)));
                this.Exit.ForeColor = System.Drawing.Color.White;
                this.Exit.Location = new System.Drawing.Point(264, 352);
                this.Exit.Name = "Exit";
                this.Exit.Size = new System.Drawing.Size(168, 44);
                this.Exit.TabIndex = 2;
                this.Exit.UseVisualStyleBackColor = false;
                this.Exit.Click += new System.EventHandler(this.Exit_Click);
                // 
                // MainMenu
                // 
                this.AutoScaleDimensions = new System.Drawing.SizeF(6F, 13F);
                this.AutoScaleMode = System.Windows.Forms.AutoScaleMode.Font;
                this.BackColor = System.Drawing.Color.FromArgb(((int)(((byte)(64)))), ((int)(((byte)(64)))), ((int)(((byte)(64)))));
                this.BackgroundImage = global::Blaze_Brigade.Resource1.MenuImage;
                this.ClientSize = new System.Drawing.Size(668, 478);
                this.ControlBox = false;
                this.Controls.Add(this.Exit);
                this.Controls.Add(this.Instructions);
                this.Controls.Add(this.Start);
                this.ForeColor = System.Drawing.Color.Transparent;
                this.Name = "MainMenu";
                this.Text = "Main Menu";
                this.ResumeLayout(false);

            }

            #endregion

            private System.Windows.Forms.Button Start;
            private System.Windows.Forms.Button Instructions;
            private System.Windows.Forms.Button Exit;
        }
    }
}